export const productsPathes = {
	fruits: "/category/fruit",
	vegetable: "/category/vegetable",
	// fish: "/category/fish",
	// dairy: "/category/dairy",
	// meat: "/category/meat",
	// spices: "/category/spices",
	// bakery: "/category/bakery",
	// beverages: "/category/beverages",
	// frozen: "/category/frozen",
	// snacks: "/category/snacks",
	// baby: "/category/baby",
	// alcohol: "/category/alcohol",
	// cleaning: "/category/cleaning",
	// pastaRice: "/category/pasta-and-Rice",
	// house: "/category/house",
	// health: "/category/health",
	// watches: "/category/watches",
	// womenClothes: "/category/women-clothes",
	// womenBags: "/category/women-bags",
	// cigarettes: "/category/cigarettes",
	productDetails: "/product-details",
	// will add other products here if nedded...
};

export enum path {
	Home = "/",
	Login = "/login",
	Profile = "/profile",
	Register = "/register",
	Messages = "/messages",
	UsersManagement = "/usersManagement",
	Fruits = "/fruits",
	AdminSettings = "/adminSettings",
	Vegetable = "/vegetable",
	AllTheOrders = "/all-orders",
	PrivacyAndPolicy = "/Privacy-and-policy",
	TermOfUse = "/term-of-use",
	CompleteProfile = "/completeProfile",
	MyOrders = "/orders",
	OrderDetails = "/orderDetails/:orderNumber",
	Checkout = "/checkout",
	Receipt = "/receipt",
	Contact = "/contact",
	About = "/about",
	Cart = "/cart",
	Png = "*",
}
