export const productsPathes = {
	fruits: "/fruit",
	vegetable: "/vegetable",
	fish: "/fish",
	dairy: "/dairy",
	meat: "/meat",
	spices: "/spices",
	bakery: "/bakery",
	beverages: "/beverages",
	frozen: "/forzen",
	snacks: "/snacks",
	baby: "/baby",
	alcohol: "/alcohol",
	cleaning: "/cleaning",
	pastaRice: "/Pasta-&-Rice",
	house: "/house",
	health: "/health",
	watches: "/watches",
	womenClothes: "/women-clothes",
	womenBags: "/women-bags",
	cigarettes: "/cigarettes",
	productDetails: "/product-details",
	// will add other products here if nedded...
};

export enum path {
	Home = "/",
	Login = "/login",
	Profile = "/profile",
	Register = "/register",
	UsersManagement = "/usersManagement",
	Fruits = "/fruits",
	AdminSettings = "/adminSettings",
	Vegetable = "/vegetable",
	AllTheOrders = "/all-orders",
	PrivacyAndPolicy = "/Privacy-and-policy",
	TermOfUse = "/term-of-use",
	CompleteProfile = "/completeProfile",
	MyOrders = "/orders",
	OrderDetails = "/orderDetails/:orderNumber",
	Checkout = "/checkout",
	Receipt = "/receipt",
	Contact = "/contact",
	About = "/about",
	Cart = "/cart",
	Png = "*",
}
