import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {
	faArrowDown,
	faBaby,
	faBagShopping,
	faBars,
	faBoxOpen,
	faBroom,
	faCalendar,
	faCar,
	faCarAlt,
	faCarBattery,
	faCartShopping,
	faChair,
	faChevronCircleRight,
	faClock,
	faCog,
	faContactCard,
	faCreditCard,
	faDrumstickBite,
	faEdit,
	faGamepad,
	faGrinStars,
	faHeart,
	faHeartPulse,
	faHome,
	faInfoCircle,
	faMoneyBillWave,
	faMotorcycle,
	faPersonWalkingArrowLoopLeft,
	faPlug,
	faShekel,
	faShirt,
	faSpa,
	faTachometer,
	faTrash,
	faTruck,
	faUserGear,
	faUserPlus,
	faUserTie,
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcon = {
	mileage: <FontAwesomeIcon icon={faTachometer} />,
	Favorite: <FontAwesomeIcon icon={faHeart} />,

	year: <FontAwesomeIcon icon={faCalendar} />,
	cleaning: <FontAwesomeIcon icon={faBroom} />,
	cars: <FontAwesomeIcon icon={faCar} />,
	brand: <FontAwesomeIcon icon={faCarAlt} />,
	electronics: <FontAwesomeIcon icon={faPlug} />,
	house: <FontAwesomeIcon icon={faChair} />,
	health: <FontAwesomeIcon icon={faHeartPulse} />,
	garden: <FontAwesomeIcon icon={faGrinStars} />,
	baby: <FontAwesomeIcon icon={faBaby} />,
	cartInoc: <FontAwesomeIcon icon={faCartShopping} />,
	userGear: <FontAwesomeIcon icon={faUserGear} />,
	electricVehicles: <FontAwesomeIcon icon={faCarBattery} />,
	motorcycles: <FontAwesomeIcon icon={faMotorcycle} />,
	logOut: <FontAwesomeIcon icon={faPersonWalkingArrowLoopLeft} />,
	shekel: <FontAwesomeIcon icon={faShekel} />,
	boxOpen: <FontAwesomeIcon icon={faBoxOpen} />,
	moneyBillWave: <FontAwesomeIcon icon={faMoneyBillWave} />,
	creditCard: <FontAwesomeIcon icon={faCreditCard} />,
	home: <FontAwesomeIcon icon={faHome} />,
	kids: <FontAwesomeIcon icon={faGamepad} />,
	trucks: <FontAwesomeIcon icon={faTruck} />,
	bikes: <FontAwesomeIcon fontWeight={100} icon={faMotorcycle} />,
	beauty: <FontAwesomeIcon icon={faSpa} />,
	meat: <FontAwesomeIcon icon={faDrumstickBite} />,
	menClothes: <FontAwesomeIcon icon={faUserTie} />,
	about: <FontAwesomeIcon icon={faInfoCircle} />,
	contact: <FontAwesomeIcon icon={faContactCard} />,
	menuBars: <FontAwesomeIcon icon={faBars} />,
	trash: <FontAwesomeIcon icon={faTrash} />,
	edit: <FontAwesomeIcon icon={faEdit} />,
	setting: <FontAwesomeIcon icon={faCog} />,
	addPerson: <FontAwesomeIcon icon={faUserPlus} />,
	backButton: <FontAwesomeIcon icon={faChevronCircleRight} />,
	watches: <FontAwesomeIcon icon={faClock} />,
	womenClothes: <FontAwesomeIcon icon={faShirt} />,
	womenBags: <FontAwesomeIcon icon={faBagShopping} />,
	arrowDown: <FontAwesomeIcon icon={faArrowDown} />,
};
