import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {
	faAppleWhole,
	faArrowDown,
	faBaby,
	faBagShopping,
	faBars,
	faBottleWater,
	faBowlFood,
	faBoxOpen,
	faBroom,
	faCalendar,
	faCar,
	faCarAlt,
	faCarrot,
	faCartShopping,
	faChair,
	faChampagneGlasses,
	faChevronCircleRight,
	faClock,
	faCog,
	faContactCard,
	faCow,
	faCreditCard,
	faDrumstickBite,
	faEdit,
	faFishFins,
	faHeartPulse,
	faHome,
	faIceCream,
	faInfoCircle,
	faListCheck,
	faMillSign,
	faMoneyBillWave,
	faMortarPestle,
	faPersonWalkingArrowLoopLeft,
	faShekel,
	faShirt,
	faSmoking,
	faSnowflake,
	faTachometer,
	faTrash,
	faUserGear,
	faUserPlus,
	faWheatAwn,
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcon = {
	mileage: <FontAwesomeIcon icon={faTachometer} />,
	year: <FontAwesomeIcon icon={faCalendar} />,
	cleaning: <FontAwesomeIcon icon={faBroom} />,
	cars: <FontAwesomeIcon icon={faCar} />,
	brand: <FontAwesomeIcon icon={faCarAlt} />,
	pastaRice: <FontAwesomeIcon icon={faBowlFood} />,
	house: <FontAwesomeIcon icon={faChair} />,
	health: <FontAwesomeIcon icon={faHeartPulse} />,
	alcohol: <FontAwesomeIcon icon={faChampagneGlasses} />,
	baby: <FontAwesomeIcon icon={faBaby} />,
	cartInoc: <FontAwesomeIcon icon={faCartShopping} />,
	userGear: <FontAwesomeIcon icon={faUserGear} />,
	fruit: <FontAwesomeIcon icon={faAppleWhole} />,
	vegetable: <FontAwesomeIcon icon={faCarrot} />,
	logOut: <FontAwesomeIcon icon={faPersonWalkingArrowLoopLeft} />,
	shekel: <FontAwesomeIcon icon={faShekel} />,
	boxOpen: <FontAwesomeIcon icon={faBoxOpen} />,
	moneyBillWave: <FontAwesomeIcon icon={faMoneyBillWave} />,
	creditCard: <FontAwesomeIcon icon={faCreditCard} />,
	home: <FontAwesomeIcon icon={faHome} />,
	ordersList: <FontAwesomeIcon icon={faListCheck} />,
	fish: <FontAwesomeIcon icon={faFishFins} />,
	dairyProducts: <FontAwesomeIcon icon={faCow} />,
	meat: <FontAwesomeIcon icon={faDrumstickBite} />,
	spices: <FontAwesomeIcon icon={faMortarPestle} />,
	bakery: <FontAwesomeIcon icon={faWheatAwn} />,
	beverages: <FontAwesomeIcon icon={faBottleWater} />,
	frozen: <FontAwesomeIcon icon={faSnowflake} />,
	snacks: <FontAwesomeIcon icon={faIceCream} />,
	about: <FontAwesomeIcon icon={faInfoCircle} />,
	contact: <FontAwesomeIcon icon={faContactCard} />,
	menuBars: <FontAwesomeIcon icon={faBars} />,
	trash: <FontAwesomeIcon icon={faTrash} />,
	edit: <FontAwesomeIcon icon={faEdit} />,
	setting: <FontAwesomeIcon color='green' icon={faCog} />,
	addPerson: <FontAwesomeIcon icon={faUserPlus} />,
	backButton: <FontAwesomeIcon icon={faChevronCircleRight} />,
	watches: <FontAwesomeIcon icon={faClock} />,
	womenClothes: <FontAwesomeIcon icon={faShirt} />,
	cigarettes: <FontAwesomeIcon icon={faSmoking} />,
	womenBags: <FontAwesomeIcon icon={faBagShopping} />,
	arrowDown: <FontAwesomeIcon icon={faArrowDown} />,
};
