import { productsPathes } from '../routes/routes';
import { Category } from './categories';

export const postsCategory = [
    { id: 'House' },
    { id: 'Garden' },
    { id: 'Electronics' },
    { id: 'Cars' },
    { id: 'Motorcycles' },
    { id: 'Bikes' },
    { id: 'Trucks' },
    { id: 'ElectricVehicles' },
    { id: 'MenClothes' },
    { id: 'WomenClothes' },
    { id: 'WomenBags' },
    { id: 'Baby' },
    { id: 'Kids' },
    { id: 'Health' },
    { id: 'Beauty' },
    { id: 'Watches' },
    { id: 'Cleaning' },
    { id: 'Art' },
    { id: 'Gaming' },
    { id: 'RealEstate' },
    { id: 'Pets' },
    { id: 'Furniture' },
    { Art: 'Art' },
    { Gaming: 'Gaming' },
    { RealEstate: 'RealEstate' },
    { Pets: 'Pets' },
    { Furniture: 'Furniture' },
];

// ----- Category Labels -----
export const categoryLabels: Record<Category, string> = {
    House: 'مستلزمات البيت',
    Garden: 'الحديقة',
    Kids: 'ألعاب الأطفال',
    Baby: 'مستلزمات الأطفال',
    Beauty: 'مستحضرات التجميل',
    Cleaning: 'مواد التنظيف',
    Health: 'الصحة والعناية',
    Watches: 'ساعات',
    MenClothes: 'ملابس رجالية',
    WomenClothes: 'ملابس نسائية',
    WomenBags: 'حقائب نسائية',
    Cars: 'سيارات',
    Motorcycles: 'دراجات نارية',
    Trucks: 'شاحنات',
    Bikes: 'دراجات هوائية',
    ElectricVehicles: 'مركبات كهربائية',
    Electronics: 'إلكترونيات',
    Art: 'فن ومقتنيات',
    Gaming: 'ألعاب وقيمنق',
    RealEstate: 'عقارات',
    Pets: 'حيوانات ومستلزماتها',
    Furniture: 'أثاث',
};

export const categoryPathMap: Record<Category, string> = {
    House: productsPathes.house,
    Garden: productsPathes.garden,
    Electronics: productsPathes.electronics,
    Kids: productsPathes.kids,
    Baby: productsPathes.baby,
    Beauty: productsPathes.beauty,
    Cleaning: productsPathes.cleaning,
    Health: productsPathes.health,
    Watches: productsPathes.watches,
    MenClothes: productsPathes.MenClothes,
    WomenClothes: productsPathes.WomenClothes,
    WomenBags: productsPathes.WomenBags,
    Cars: productsPathes.cars,
    Motorcycles: productsPathes.motorcycles,
    Trucks: productsPathes.trucks,
    Bikes: productsPathes.bikes,
    ElectricVehicles: productsPathes.electricVehicles,
    Art: productsPathes.art,
    Gaming: productsPathes.gaming,
    RealEstate: productsPathes.realEstate,
    Pets: productsPathes.pets,
    Furniture: productsPathes.furniture,
} as const;
