import {productsPathes} from "../routes/routes";

export const postsCategory = [
	{id: "House"},
	{id: "Garden"},
	{id: "Electronics"},
	{id: "Kids"},
	{id: "Baby"},
	{id: "Beauty"},
	{id: "Cleaning"},
	{id: "Health"},
	{id: "Watches"},
	{id: "MenClothes"},
	{id: "WomenClothes"},
	{id: "Womenbags"},
	{id: "cars"},
	{id: "Motorcycles"},
	{id: "Trucks"},
	{id: "Bikes"},
	{id: "ElectricVehicles"},
];

// ----- Category Labels -----
export const categoryLabels: Record<string, string> = {
	house: "مستلزمات البيت",
	garden: "الحديقة",
	electronics: "إلكترونيات",
	kids: "ألعاب الأطفال",
	baby: "مستلزمات الأطفال",
	beauty: "مستحضرات التجميل",
	cleaning: "مواد التنظيف",
	health: "الصحة والعناية",
	watches: "ساعات",
	menClothes: "ملابس رجالية",
	womenClothes: "ملابس نسائية",
	womenBags: "حقائب نسائية",
	cars: "سيارات",
	motorcycles: "دراجات نارية",
	trucks: "شاحنات",
	bikes: "دراجات هوائية",
	electricVehicles: "مركبات كهربائية",
} as const;

export const categoryPathMap: Record<string, string> = {
	house: productsPathes.house,
	garden: productsPathes.garden,
	electronics: productsPathes.electronics,
	kids: productsPathes.kids,
	baby: productsPathes.baby,
	beauty: productsPathes.beauty,
	cleaning: productsPathes.cleaning,
	health: productsPathes.health,
	watches: productsPathes.watches,
	menClothes: productsPathes.menClothes,
	womenClothes: productsPathes.womenClothes,
	womenBags: productsPathes.womenBags,
	cars: productsPathes.cars,
	motorcycles: productsPathes.motorcycles,
	trucks: productsPathes.trucks,
	bikes: productsPathes.bikes,
	electricVehicles: productsPathes.electricVehicles,
} as const;
