import {productsPathes} from "../routes/routes";

export const productCategories = [
	{id: "house", label: "مستلزمات البيت"},
	{id: "garden", label: "الحديقة"},
	{id: "electronics", label: "إلكترونيات"},
	{id: "kids", label: "ألعاب الأطفال"},
	{id: "baby", label: "مستلزمات الأطفال"},
	{id: "beauty", label: "مستحضرات التجميل"},
	{id: "cleaning", label: "مواد التنظيف"},
	{id: "health", label: "الصحة والعناية"},
	{id: "watches", label: "ساعات"},
	{id: "menClothes", label: "ملابس رجالية"},
	{id: "womenClothes", label: "ملابس نسائية"},
	{id: "womenBags", label: "حقائب نسائية"},
	{id: "cars", label: "سيارات"},
	{id: "motorcycles", label: "دراجات نارية"},
	{id: "trucks", label: "شاحنات"},
	{id: "bikes", label: "دراجات هوائية"},
	{id: "electricVehicles", label: "مركبات كهربائية"},
];

// ----- Category Labels -----
export const categoryLabels: Record<string, string> = {
	house: "مستلزمات البيت",
	garden: "الحديقة",
	electronics: "إلكترونيات",
	kids: "ألعاب الأطفال",
	baby: "مستلزمات الأطفال",
	beauty: "مستحضرات التجميل",
	cleaning: "مواد التنظيف",
	health: "الصحة والعناية",
	watches: "ساعات",
	menClothes: "ملابس رجالية",
	womenClothes: "ملابس نسائية",
	womenBags: "حقائب نسائية",
	cars: "سيارات",
	motorcycles: "دراجات نارية",
	trucks: "شاحنات",
	bikes: "دراجات هوائية",
	electricVehicles: "مركبات كهربائية",
};

export const categoryPathMap: Record<string, string> = {
	house: productsPathes.house,
	garden: productsPathes.garden,
	electronics: productsPathes.electronics,
	kids: productsPathes.kids,
	baby: productsPathes.baby,
	beauty: productsPathes.beauty,
	cleaning: productsPathes.cleaning,
	health: productsPathes.health,
	watches: productsPathes.watches,
	menClothes: productsPathes.menClothes,
	womenClothes: productsPathes.womenClothes,
	womenBags: productsPathes.womenBags,
	cars: productsPathes.cars,
	motorcycles: productsPathes.motorcycles,
	trucks: productsPathes.trucks,
	bikes: productsPathes.bikes,
	electricVehicles: productsPathes.electricVehicles,
};
