export const productCategories = [
	{id: "Fruit", label: "פירות"},
	{id: "Vegetable", label: "ירקות"},
	{id: "Dairy", label: "מוצרי חלב"},
	{id: "Meat", label: "בשר"},
	{id: "Fish", label: "דגים"},
	{id: "Spices", label: "תבלינים"},
	{id: "Bakery", label: "מאפים"},
	{id: "Beverages", label: "משקאות"},
	{id: "Frozen", label: "מוצרים קפואים"},
	{id: "Snacks", label: "חטיפים"},
	{id: "Baby", label: "מוצרים לתינוק"},
	{id: "Alcohol", label: "אלכהול"},
	{id: "Cleaning", label: "חומרי ניקוי"},
	{id: "Pasta & Rice", label: "פסטה ואורז"},
	{id: "Home", label: "פריטי הבית"},
	{id: "Health", label: "מוצרי בריאות"},
	{id: "Watches", label: "שעונים"},
	{id: "Women-clothes", label: "ביגוד נשים"},
	{id: "Women-bags", label: "תיקים לנשים"},
	{id: "Cigarettes", label: "סיגריות"},
];